### ISSUE TITLE
SyntaxError v3

### ISSUE THREAD

**Issue by sjlu** [niftylettuce/email-templates#246]
```
0|web      | /Users/sjlu/Code/interseller/node_modules/email-templates/index.js:86
0|web      |     return new Promise(async (resolve, reject) => {
0|web      |                              ^
0|web      | SyntaxError: Unexpected token (
```

```
node --version
v6.11.4
```

Is there a minimum version to running v3?

**Comment by OmgImAlexis** [comment]
Node v8.3 is required.

**Comment by sjlu** [comment]
Got it, probably would be a good idea to mention that in the docs!

**Comment by OmgImAlexis** [comment]
Node should have actually thrown an error while installing since the `engines:node` is set.

Ref: https://github.com/niftylettuce/email-templates/blob/master/package.json#L51

**Comment by niftylettuce** [comment]
Also hopefully to prevent other users from this headache, I've added a note regarding Node v7.6.0+ requirement to README per https://github.com/niftylettuce/email-templates/commit/5260d65d56c259af8d58ddbaee6912da13463d16.

**Comment by niftylettuce** [comment]
can you please try v3.1.5? npm install email-templates@latest or yarn add email-templates@latest. this package now supports Node v6.4.0+. I've also updated README with this note that v6.4.0+ is a requirement (instead of 7.x)  also please see v2 to v3 upgrade guide at <https://github.com/niftylettuce/email-templates#v3-breaking-changes>

**Comment by sjlu** [comment]
Just migrated everything over and it works great 👍
