### ISSUE TITLE
Directory of call

### ISSUE THREAD

**Issue by thatisuday** [niftylettuce/email-templates#275]
If you are running node command from directory where `email.js` file is not available for example, `node src/email.js` considering all code to send email contain inside `email.js`, this library does not find email templates directory `emails`.

Why does it matter, from which directory you are calling a file?

**Comment by niftylettuce** [comment]
It is because we use `path.resolve` with a default path of `./emails`.

If you want to have it bound to a specific folder, please pass a custom path <https://github.com/niftylettuce/email-templates/blob/master/src/index.js#L33-L34>.  You may also want to pass a custom build path too <https://github.com/niftylettuce/email-templates/blob/master/src/index.js#L66-L68>.

If you want to submit a pull request so that by default it searches up to the root directory of the project then I'd gladly accept.

**Comment by niftylettuce** [comment]
@thatisuday are you interested in submitting a pull request? You could use this https://github.com/sindresorhus/find-up and reference https://github.com/sindresorhus/pkg-conf probably to find the folder named "emails".  Also might want to do the same for custom build path.  See my last comment.

**Comment by niftylettuce** [comment]
This is now fixed in v3.6.2 🎉 - please install via `npm install email-templates@latest` or `yarn add email-templates@latest`.  It by default uses `pkg-dir` (see <https://github.com/sindresorhus/pkg-dir>) to get the root directory of the project, and then uses `path.join(root, 'emails')` to get the path to the emails directory in the root folder.

**Comment by niftylettuce** [comment]
I had to unpublish v3.6.2 due to this breaking issue with serverless apps <https://github.com/niftylettuce/email-templates/commit/bd499e361aab22125e67cdb15ee58f24e2a7265d#commitcomment-29050761.  I've re-published this in v4.0.0.
