### ISSUE TITLE
Error: ENOENT for index.swig?

### ISSUE THREAD

**Issue by israelidanny** [niftylettuce/email-templates#328]
I'm trying to use this with swig. I was on 2.x branch and it worked. I did some rewriting, to try to make v5 work. I'm getting this kind of error:
```
Error: ENOENT: no such file or directory, open '/Users/danny/src/project/mail/templates/comment/index.swig
```

I'm not specifying any unusual settings otherwise. There is an `html.swig` file at that path, and I'm not sure why it would look for `index.swig`? Is this expected behaviour? Any help would be appreciated.

**Comment by niftylettuce** [comment]
It's probably due to this package <https://github.com/niftylettuce/get-paths/blob/master/index.js#L13> specifically trying to fetch the `index.swig` file.

Are you using just the `render` method? If so that is why it is looking for `index.swig` - see https://github.com/niftylettuce/email-templates/blob/master/src/index.js#L109-L117. Notice htat the README shows https://github.com/niftylettuce/email-templates#render-html-andor-text using `/html`.

**Comment by israelidanny** [comment]
@niftylettuce alright, thanks a lot! that helped! A related (but maybe unrelated) question:
v2.x used to automatically pull up `style.swig`, but v5.x seems not to. Is this by design? Is there a way to automatically include style.swig like it used to?

**Comment by niftylettuce** [comment]
@israelidanny see <https://github.com/niftylettuce/email-templates#automatic-inline-css-via-stylesheets>

You'll need to add in your `html.swig` template file, in the `<head>` section a `<style>` tag as that link suggests.  You'll also need to ensure your `style.swig` is compiled to `style.css`, and use the `.css` version in the `href` attribute of the `<style>` tag you add.

**Comment by israelidanny** [comment]
@niftylettuce thanks a lot! everything works now!
