### ISSUE TITLE
missing typescript definitions

### ISSUE THREAD

**Issue by simllll** [niftylettuce/email-templates#367]
There is @types/email-templates, but it' really outdated and incomplete. Would be great if this project will add typescript definitions bundled with it.

Furthermore I would like to add some variable wordings which kinda confused me:
* locals .. is actually the data that is passed to the template
* template .. is the folder where the templates are in
* type .. is the name of the template

Regards
Simon

**Comment by niftylettuce** [comment]
I do not support TypeScript.  It is bad for the community and open-source.

**Comment by simllll** [comment]
Alright,no worries. Just our of curiosity, why do you think it's bad for the community and for the open source world? What do you think about flow or other alternatives?

**Comment by niftylettuce** [comment]
The barrier to entry for someone contributing to open source and opening a pull request is already high.  If you add on another layer of complexity, e.g. TypeScript, CoffeeScript, WhateverScript, then it only makes it harder.  I also do not think TypeScript is necessary for such simple projects and packages.  The only "compiler" I support across the entire community is Babel, and that is because it allows us to compile towards browser versions and Node version targets in order for us to support a range of projects and lint them as well.

**Comment by maplesteve** [comment]
@niftylettuce I think this is not about _migrating_ this project to TypeScript, but just to make it more usable for people who use it in projects written in TypeScript.

**Comment by niftylettuce** [comment]
I don't support TypeScript in any case across any of my projects on GitHub, regardless if it's to help make it more usable for others or not.  TypeScript is overkill, bloat, and not community-friendly nor maintainer-friendly.

After managing and contributing to thousands of packages for nearly a decade now - I refuse to use or support anything but pure JS.
